#!/bin/bash

# migrates code to remote machine and runs compilation script

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/../../config.txt

rsync -avz --delete $BASE_PROJECT_DIR/ $CAR_REMOTE_PROJECT_ADDRESS

ssh $CAR_REMOTE_ADDRESS $CAR_PROJECT_DIR/car/scripts/car_arduino_upload
