#!/bin/bash

# copies images from the remote car filder

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/../../config.txt

rsync -avz --delete $CAR_USR@$CAR_ADDRESS:$CAR_TEST_IMAGES_DIR $BASE_TEST_IMAGES_DIR

