#!/bin/bash

# re-define echo to prepend with car_remote and colour green to indicate remoteness
function echo {
	builtin echo -e '\e[92mcar_remote: ' "$@" ;
}

echo "Compiling code..."
echo "Restarting persistent service..."
echo "Done!"
