#!/bin/bash

# compiles the arduino code and uploads to the hardware

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/../../config.txt

# re-define echo to prepend with car_remote and colour green to indicate remoteness
function echo {
	builtin echo -e '\e[92mcar_remote: ' "$@" ;
}

echo "Uploading to arduino..."

cd $DIR/../hardware

make clean
make flash
